### ISSUE TITLE
Fix pasring package.json 

### ISSUE THREAD

**Issue by wick3ds0ul** [sonatype-nexus-community/nexus-cli#7]
I am using the [latest](https://download.sonatype.com/clm/scanner/latest.jar) nexus cli to scan a nodejs project.
It fails with this error in CI:
```
./node_modules/resolve/test/resolver/malformed_package_json/package.json
Error:  java.io.EOFException: End of input at line 2 column 1 path $.
Error:  Error details:
java.lang.RuntimeException: java.io.EOFException: End of input at line 2 column 1 path $.
	at com.sonatype.insight.scan.file.JavascriptPackageJsonProcessor.process(JavascriptPackageJsonProcessor.java:34)
	at com.sonatype.insight.scan.file.ManifestContentProcessor.setScanItemContent(ManifestContentProcessor.java:237)
	at com.sonatype.insight.scan.file.FileVisitor.visitFile(FileVisitor.java:281)
	at com.sonatype.insight.scan.file.FileWalker.doWalk(FileWalker.java:86)
	at com.sonatype.insight.scan.file.FileWalker.doWalk(FileWalker.java:75)
	at com.sonatype.insight.scan.file.FileWalker.doWalk(FileWalker.java:75)
	at com.sonatype.insight.scan.file.FileWalker.doWalk(FileWalker.java:75)
	at com.sonatype.insight.scan.file.FileWalker.doWalk(FileWalker.java:75)
	at com.sonatype.insight.scan.file.FileWalker.doWalk(FileWalker.java:75)
	at com.sonatype.insight.scan.file.FileWalker.doWalk(FileWalker.java:75)
	at com.sonatype.insight.scan.file.FileWalker.walk(FileWalker.java:35)
	at com.sonatype.insight.scan.file.FileScanner.scan(FileScanner.java:93)
	at com.sonatype.insight.scan.cli.Scanner.scan(Scanner.java:117)
	at com.sonatype.insight.scan.cli.AbstractPolicyEvaluator.scan(AbstractPolicyEvaluator.java:219)
	at com.sonatype.insight.scan.cli.AbstractPolicyEvaluator.run(AbstractPolicyEvaluator.java:77)
	at com.sonatype.insight.scan.cli.PolicyEvaluator.run(PolicyEvaluator.java:112)
	at com.sonatype.insight.scan.cli.PolicyEvaluatorCli.run(PolicyEvaluatorCli.java:56)
	at com.sonatype.insight.scan.cli.PolicyEvaluatorCli.main(PolicyEvaluatorCli.java:47)
Caused by: com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 2 column 1 path $.
	at com.google.gson.Gson.fromJson(Gson.java:973)
	at com.google.gson.Gson.fromJson(Gson.java:901)
	at com.sonatype.insight.scan.file.JavascriptPackageJsonProcessor.process(JavascriptPackageJsonProcessor.java:30)
	... 17 common frames omitted
Caused by: java.io.EOFException: End of input at line 2 column 1 path $.
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1395)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:493)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:413)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
	at com.google.gson.Gson.fromJson(Gson.java:963)
	... 19 common frames omitted
```
There seems to be a missing `}` in this [thread](https://github.com/browserify/resolve/issues/271). Can this be ignored while scanning `node_modules`?

**Comment by ghost** [comment]
Ironically, this is a test file ..;. and deliberately malformed :D  I just encountered that also *sigh*  I'm trying the --ignore-scanning-errors to see if that works.  Will update, if so.

That does seem to work... Might be too big a hammer?  (it does still show an exception, but it continues anyway).  It looks like there might also be options to explicitly exclude specific files (or directories) -- haven't explored that yet.
